[tool.bumpversion]
current_version = "0.2.0"
commit = true
tag = true
tag_name = "v{new_version}"
message = "Bump version: {current_version} -> {new_version}"

[[tool.bumpversion.files]]
filename = "tdaspop/version.py"
search = '__VERSION__ = "{current_version}"'
replace = '__VERSION__ = "{new_version}"'
